2022-03-03 14:35:49,158 INFO    MainThread:524 [internal.py:wandb_internal():91] W&B internal server running at pid: 524, started at: 2022-03-03 14:35:49.158178
2022-03-03 14:35:49,160 DEBUG   HandlerThread:524 [handler.py:handle_request():120] handle_request: check_version
2022-03-03 14:35:49,160 INFO    WriterThread:524 [datastore.py:open_for_write():77] open: /workspace/graph-neural-pde/src/wandb/run-20220303_143548-hy9j6vso/run-hy9j6vso.wandb
2022-03-03 14:35:49,161 DEBUG   SenderThread:524 [sender.py:send():160] send: header
2022-03-03 14:35:49,161 DEBUG   SenderThread:524 [sender.py:send():160] send: request
2022-03-03 14:35:49,161 DEBUG   SenderThread:524 [sender.py:send_request():169] send_request: check_version
2022-03-03 14:35:49,375 DEBUG   SenderThread:524 [sender.py:send():160] send: run
2022-03-03 14:35:49,939 INFO    SenderThread:524 [sender.py:_start_run_threads():654] run started: hy9j6vso with start time 1646318148
2022-03-03 14:35:49,939 DEBUG   SenderThread:524 [sender.py:send():160] send: summary
2022-03-03 14:35:49,940 INFO    SenderThread:524 [sender.py:_save_file():781] saving file wandb-summary.json with policy end
2022-03-03 14:35:49,945 DEBUG   HandlerThread:524 [handler.py:handle_request():120] handle_request: run_start
2022-03-03 14:35:50,801 WARNING MainThread:524 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-03-03 14:35:50,983 DEBUG   HandlerThread:524 [meta.py:__init__():39] meta init
2022-03-03 14:35:50,983 DEBUG   HandlerThread:524 [meta.py:__init__():53] meta init done
2022-03-03 14:35:50,983 DEBUG   HandlerThread:524 [meta.py:probe():210] probe
2022-03-03 14:35:50,984 DEBUG   HandlerThread:524 [meta.py:_setup_git():200] setup git
2022-03-03 14:35:50,994 DEBUG   HandlerThread:524 [meta.py:_setup_git():207] setup git done
2022-03-03 14:35:50,994 DEBUG   HandlerThread:524 [meta.py:_save_pip():57] save pip
2022-03-03 14:35:50,995 DEBUG   HandlerThread:524 [meta.py:_save_pip():71] save pip done
2022-03-03 14:35:50,995 DEBUG   HandlerThread:524 [meta.py:_save_conda():78] save conda
2022-03-03 14:35:51,345 WARNING MainThread:524 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-03-03 14:35:51,345 ERROR   MainThread:524 [internal.py:wandb_internal():149] Internal process interrupted.
2022-03-03 14:35:51,372 DEBUG   HandlerThread:524 [meta.py:_save_conda():86] save conda done
2022-03-03 14:35:51,372 DEBUG   HandlerThread:524 [meta.py:probe():252] probe done
2022-03-03 14:35:51,374 INFO    HandlerThread:524 [handler.py:finish():624] shutting down handler
2022-03-03 14:35:51,381 INFO    WriterThread:524 [datastore.py:close():258] close: /workspace/graph-neural-pde/src/wandb/run-20220303_143548-hy9j6vso/run-hy9j6vso.wandb
2022-03-03 14:35:51,979 INFO    SenderThread:524 [sender.py:finish():884] shutting down sender
2022-03-03 14:35:54,704 INFO    MainThread:524 [internal.py:handle_exit():78] Internal process exited
