2022-03-27 09:33:03,338 INFO    MainThread:1728 [wandb_setup.py:_flush():69] setting env: {}
2022-03-27 09:33:03,338 INFO    MainThread:1728 [wandb_setup.py:_flush():69] setting login settings: {}
2022-03-27 09:33:03,338 INFO    MainThread:1728 [wandb_init.py:_log_setup():336] Logging user logs to /workspace/graph-neural-pde/src/wandb/run-20220327_093303-vanilla alpha_ = 0.9 alpha = default dopri5 v = ones test3/logs/debug.log
2022-03-27 09:33:03,338 INFO    MainThread:1728 [wandb_init.py:_log_setup():337] Logging internal logs to /workspace/graph-neural-pde/src/wandb/run-20220327_093303-vanilla alpha_ = 0.9 alpha = default dopri5 v = ones test3/logs/debug-internal.log
2022-03-27 09:33:03,339 INFO    MainThread:1728 [wandb_init.py:init():369] calling init triggers
2022-03-27 09:33:03,339 INFO    MainThread:1728 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2022-03-27 09:33:03,339 INFO    MainThread:1728 [wandb_init.py:init():418] starting backend
2022-03-27 09:33:03,339 INFO    MainThread:1728 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-27 09:33:03,352 INFO    MainThread:1728 [backend.py:ensure_launched():123] starting backend process...
2022-03-27 09:33:03,370 INFO    MainThread:1728 [backend.py:ensure_launched():128] started backend process with pid: 1754
2022-03-27 09:33:03,372 INFO    MainThread:1728 [wandb_init.py:init():423] backend started and connected
2022-03-27 09:33:03,375 INFO    MainThread:1728 [wandb_init.py:init():465] updated telemetry
2022-03-27 09:33:03,377 INFO    MainThread:1728 [wandb_init.py:init():484] communicating current version
2022-03-27 09:33:04,506 INFO    MainThread:1728 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-27 09:33:04,507 INFO    MainThread:1728 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2022-03-27 09:33:04,922 INFO    MainThread:1728 [wandb_init.py:init():522] starting run threads in backend
2022-03-27 09:33:07,787 INFO    MainThread:1728 [wandb_run.py:_console_start():1524] atexit reg
2022-03-27 09:33:07,788 INFO    MainThread:1728 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2022-03-27 09:33:07,793 INFO    MainThread:1728 [wandb_run.py:_redirect():1376] Redirecting console.
2022-03-27 09:33:07,796 INFO    MainThread:1728 [wandb_run.py:_redirect():1438] Redirects installed.
2022-03-27 09:33:07,796 INFO    MainThread:1728 [wandb_init.py:init():546] run started, returning control to user process
2022-03-27 09:33:10,718 INFO    MainThread:1728 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2022-03-27 09:33:10,720 INFO    MainThread:1728 [wandb_run.py:_restore():1466] restore
2022-03-27 09:33:13,131 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 909
  total_bytes: 909
}

2022-03-27 09:33:13,944 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 909
  total_bytes: 909
}

2022-03-27 09:33:14,452 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6949
  total_bytes: 6949
}

2022-03-27 09:33:14,554 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6949
  total_bytes: 6949
}

2022-03-27 09:33:14,656 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6949
  total_bytes: 6949
}

2022-03-27 09:33:14,758 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6949
  total_bytes: 6949
}

2022-03-27 09:33:14,861 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6949
  total_bytes: 6949
}

2022-03-27 09:33:14,963 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6949
  total_bytes: 6949
}

2022-03-27 09:33:15,065 INFO    MainThread:1728 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6949
  total_bytes: 6949
}

2022-03-27 09:33:16,427 INFO    MainThread:1728 [wandb_run.py:_show_files():1838] logging synced files
